#:schema node_modules/wrangler/config-schema.json
name = "zhuanhuan"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "4318a2c0e3344ad9be8e0799230f137e" }
]

[assets]
directory = "./public"
